function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = 0; // obj_char
	global.__objectDepths[1] = 0; // obj_chardisappear
	global.__objectDepths[2] = 1000; // obj_bound
	global.__objectDepths[3] = 0; // obj_move
	global.__objectDepths[4] = 10; // obj_doorR
	global.__objectDepths[5] = 10; // obj_doorL
	global.__objectDepths[6] = 10; // obj_doorLopen
	global.__objectDepths[7] = 100; // obj_doorleftshad
	global.__objectDepths[8] = -10000; // obj_actionbox
	global.__objectDepths[9] = -10001; // obj_talkbut
	global.__objectDepths[10] = -10001; // obj_lookbut
	global.__objectDepths[11] = -10001; // obj_usebut
	global.__objectDepths[12] = -10001; // obj_Savebut
	global.__objectDepths[13] = -10001; // obj_Loadbut
	global.__objectDepths[14] = 0; // obj_walktimerdoorL
	global.__objectDepths[15] = -1000; // obj_topwall
	global.__objectDepths[16] = -10000000; // obj_cursor
	global.__objectDepths[17] = -10000000; // obj_cursorshad
	global.__objectDepths[18] = -10002; // obj_talkbutpress
	global.__objectDepths[19] = -10002; // obj_lookbutpress
	global.__objectDepths[20] = -10002; // obj_usebutpress
	global.__objectDepths[21] = -10002; // obj_savebutpress
	global.__objectDepths[22] = -10002; // obj_loadbutpress
	global.__objectDepths[23] = 0; // obj_saveconfirm
	global.__objectDepths[24] = 0; // obj_savebox
	global.__objectDepths[25] = 0; // obj_Adraw
	global.__objectDepths[26] = 0; // obj_adraw
	global.__objectDepths[27] = 0; // obj_Bdraw
	global.__objectDepths[28] = 0; // obj_bdraw
	global.__objectDepths[29] = 0; // obj_Cdraw
	global.__objectDepths[30] = 0; // obj_cdraw
	global.__objectDepths[31] = 0; // obj_Ddraw
	global.__objectDepths[32] = 0; // obj_ddraw
	global.__objectDepths[33] = 0; // obj_Edraw
	global.__objectDepths[34] = 0; // obj_edraw
	global.__objectDepths[35] = 0; // obj_Fdraw
	global.__objectDepths[36] = 0; // obj_fdraw
	global.__objectDepths[37] = 0; // obj_Gdraw
	global.__objectDepths[38] = 0; // obj_gdraw
	global.__objectDepths[39] = 0; // obj_Hdraw
	global.__objectDepths[40] = 0; // obj_hdraw
	global.__objectDepths[41] = 0; // obj_Idraw
	global.__objectDepths[42] = 0; // obj_idraw
	global.__objectDepths[43] = 0; // obj_Jdraw
	global.__objectDepths[44] = 0; // obj_jdraw
	global.__objectDepths[45] = 0; // obj_Kdraw
	global.__objectDepths[46] = 0; // obj_kdraw
	global.__objectDepths[47] = 0; // obj_Ldraw
	global.__objectDepths[48] = 0; // obj_ldraw
	global.__objectDepths[49] = 0; // obj_Mdraw
	global.__objectDepths[50] = 0; // obj_mdraw
	global.__objectDepths[51] = 0; // obj_Ndraw
	global.__objectDepths[52] = 0; // obj_ndraw
	global.__objectDepths[53] = 0; // obj_Odraw
	global.__objectDepths[54] = 0; // obj_odraw
	global.__objectDepths[55] = 0; // obj_Pdraw
	global.__objectDepths[56] = 0; // obj_pdraw
	global.__objectDepths[57] = 0; // obj_Qdraw
	global.__objectDepths[58] = 0; // obj_qdraw
	global.__objectDepths[59] = 0; // obj_Rdraw
	global.__objectDepths[60] = 0; // obj_rdraw
	global.__objectDepths[61] = 0; // obj_Sdraw
	global.__objectDepths[62] = 0; // obj_sdraw
	global.__objectDepths[63] = 0; // obj_Tdraw
	global.__objectDepths[64] = 0; // obj_tdraw
	global.__objectDepths[65] = 0; // obj_Udraw
	global.__objectDepths[66] = 0; // obj_udraw
	global.__objectDepths[67] = 0; // obj_Vdraw
	global.__objectDepths[68] = 0; // obj_vdraw
	global.__objectDepths[69] = 0; // obj_Wdraw
	global.__objectDepths[70] = 0; // obj_wdraw
	global.__objectDepths[71] = 0; // obj_Xdraw
	global.__objectDepths[72] = 0; // obj_xdraw
	global.__objectDepths[73] = 0; // obj_Ydraw
	global.__objectDepths[74] = 0; // obj_ydraw
	global.__objectDepths[75] = 0; // obj_Zdraw
	global.__objectDepths[76] = 0; // obj_zdraw
	global.__objectDepths[77] = 0; // obj_0draw
	global.__objectDepths[78] = 0; // obj_)draw
	global.__objectDepths[79] = 0; // obj_1draw
	global.__objectDepths[80] = 0; // obj_!draw
	global.__objectDepths[81] = 0; // obj_2draw
	global.__objectDepths[82] = 0; // obj_@draw
	global.__objectDepths[83] = 0; // obj_3draw
	global.__objectDepths[84] = 0; // obj_#draw
	global.__objectDepths[85] = 0; // obj_4draw
	global.__objectDepths[86] = 0; // obj_$draw
	global.__objectDepths[87] = 0; // obj_5draw
	global.__objectDepths[88] = 0; // obj_%draw
	global.__objectDepths[89] = 0; // obj_6draw
	global.__objectDepths[90] = 0; // obj_^draw
	global.__objectDepths[91] = 0; // obj_7draw
	global.__objectDepths[92] = 0; // obj_&draw
	global.__objectDepths[93] = 0; // obj_8draw
	global.__objectDepths[94] = 0; // obj_9draw
	global.__objectDepths[95] = 0; // obj_(draw
	global.__objectDepths[96] = 0; // obj_deletedraw
	global.__objectDepths[97] = 0; // obj_cleardraw


	global.__objectNames[0] = "obj_char";
	global.__objectNames[1] = "obj_chardisappear";
	global.__objectNames[2] = "obj_bound";
	global.__objectNames[3] = "obj_move";
	global.__objectNames[4] = "obj_doorR";
	global.__objectNames[5] = "obj_doorL";
	global.__objectNames[6] = "obj_doorLopen";
	global.__objectNames[7] = "obj_doorleftshad";
	global.__objectNames[8] = "obj_actionbox";
	global.__objectNames[9] = "obj_talkbut";
	global.__objectNames[10] = "obj_lookbut";
	global.__objectNames[11] = "obj_usebut";
	global.__objectNames[12] = "obj_Savebut";
	global.__objectNames[13] = "obj_Loadbut";
	global.__objectNames[14] = "obj_walktimerdoorL";
	global.__objectNames[15] = "obj_topwall";
	global.__objectNames[16] = "obj_cursor";
	global.__objectNames[17] = "obj_cursorshad";
	global.__objectNames[18] = "obj_talkbutpress";
	global.__objectNames[19] = "obj_lookbutpress";
	global.__objectNames[20] = "obj_usebutpress";
	global.__objectNames[21] = "obj_savebutpress";
	global.__objectNames[22] = "obj_loadbutpress";
	global.__objectNames[23] = "obj_saveconfirm";
	global.__objectNames[24] = "obj_savebox";
	global.__objectNames[25] = "obj_Adraw";
	global.__objectNames[26] = "obj_adraw";
	global.__objectNames[27] = "obj_Bdraw";
	global.__objectNames[28] = "obj_bdraw";
	global.__objectNames[29] = "obj_Cdraw";
	global.__objectNames[30] = "obj_cdraw";
	global.__objectNames[31] = "obj_Ddraw";
	global.__objectNames[32] = "obj_ddraw";
	global.__objectNames[33] = "obj_Edraw";
	global.__objectNames[34] = "obj_edraw";
	global.__objectNames[35] = "obj_Fdraw";
	global.__objectNames[36] = "obj_fdraw";
	global.__objectNames[37] = "obj_Gdraw";
	global.__objectNames[38] = "obj_gdraw";
	global.__objectNames[39] = "obj_Hdraw";
	global.__objectNames[40] = "obj_hdraw";
	global.__objectNames[41] = "obj_Idraw";
	global.__objectNames[42] = "obj_idraw";
	global.__objectNames[43] = "obj_Jdraw";
	global.__objectNames[44] = "obj_jdraw";
	global.__objectNames[45] = "obj_Kdraw";
	global.__objectNames[46] = "obj_kdraw";
	global.__objectNames[47] = "obj_Ldraw";
	global.__objectNames[48] = "obj_ldraw";
	global.__objectNames[49] = "obj_Mdraw";
	global.__objectNames[50] = "obj_mdraw";
	global.__objectNames[51] = "obj_Ndraw";
	global.__objectNames[52] = "obj_ndraw";
	global.__objectNames[53] = "obj_Odraw";
	global.__objectNames[54] = "obj_odraw";
	global.__objectNames[55] = "obj_Pdraw";
	global.__objectNames[56] = "obj_pdraw";
	global.__objectNames[57] = "obj_Qdraw";
	global.__objectNames[58] = "obj_qdraw";
	global.__objectNames[59] = "obj_Rdraw";
	global.__objectNames[60] = "obj_rdraw";
	global.__objectNames[61] = "obj_Sdraw";
	global.__objectNames[62] = "obj_sdraw";
	global.__objectNames[63] = "obj_Tdraw";
	global.__objectNames[64] = "obj_tdraw";
	global.__objectNames[65] = "obj_Udraw";
	global.__objectNames[66] = "obj_udraw";
	global.__objectNames[67] = "obj_Vdraw";
	global.__objectNames[68] = "obj_vdraw";
	global.__objectNames[69] = "obj_Wdraw";
	global.__objectNames[70] = "obj_wdraw";
	global.__objectNames[71] = "obj_Xdraw";
	global.__objectNames[72] = "obj_xdraw";
	global.__objectNames[73] = "obj_Ydraw";
	global.__objectNames[74] = "obj_ydraw";
	global.__objectNames[75] = "obj_Zdraw";
	global.__objectNames[76] = "obj_zdraw";
	global.__objectNames[77] = "obj_0draw";
	global.__objectNames[78] = "obj_)draw";
	global.__objectNames[79] = "obj_1draw";
	global.__objectNames[80] = "obj_!draw";
	global.__objectNames[81] = "obj_2draw";
	global.__objectNames[82] = "obj_@draw";
	global.__objectNames[83] = "obj_3draw";
	global.__objectNames[84] = "obj_#draw";
	global.__objectNames[85] = "obj_4draw";
	global.__objectNames[86] = "obj_$draw";
	global.__objectNames[87] = "obj_5draw";
	global.__objectNames[88] = "obj_%draw";
	global.__objectNames[89] = "obj_6draw";
	global.__objectNames[90] = "obj_^draw";
	global.__objectNames[91] = "obj_7draw";
	global.__objectNames[92] = "obj_&draw";
	global.__objectNames[93] = "obj_8draw";
	global.__objectNames[94] = "obj_9draw";
	global.__objectNames[95] = "obj_(draw";
	global.__objectNames[96] = "obj_deletedraw";
	global.__objectNames[97] = "obj_cleardraw";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
